# Generated by Django 5.1.6 on 2025-02-17 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('imagen', models.ImageField(upload_to='formacion/images')),
                ('date', models.DateField(verbose_name=datetime.date.today)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
